name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production  # <-- matches your GitHub environment name exactly

    steps:
      - uses: actions/checkout@v3

      - name: Show secret example
        run: echo "API_KEY is $API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}
